# Site settings
title: Adam-ondi-Ahman.glass
email: 
description: > # this means to ignore newlines until "baseurl:"
  The Fall of the Great and Spacious Building is upon us. Prepare: our journey to Zion has begun.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
exclude: ['node_modules', 'Gruntfile.js', 'package.json']

highlighter: pygments

# YB Settings
excerpt_separator: <!-- more -->
paginate: 5
comments: false

gems: [jekyll-paginate]
