# Site settings
title: Book of Mormon Prophecy
email: 
description: > # this means to ignore newlines until "baseurl:"
  The Red Pill: Formulated Specially For Mormons
url: "http://www.bookofmormonprophecy.info" # the base hostname & protocol for your site
# baseurl: "/bookofmormon/" # the subpath of your site, e.g. /blog/
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: the_awakening
github_username: 

# Build settings
markdown: kramdown
exclude: ['node_modules', 'Gruntfile.js', 'package.json']

highlighter: rouge

# YB Settings
excerpt_separator: <!-- more -->
paginate: 5
comments: false

gems: [jekyll-paginate]
